hotel/urls.py
from django.urls import path
from .views import index, auth, account, customer, notice, room, book, order, sql
from .views import test

urlpatterns = [
	path("", index.index, name="index"),

	path("test/", test.test),

	path("book/", book.BookList.as_view(), name="book_list"),
	path("book/detail/", book.book_detail, name="book_detail"),
	path("book/check/", book.BookCheck.as_view(), name="book_check"),

	path("order/", order.OrderList.as_view(), name="order_list"),
	path("order/<int:pk>/detail/", order.OrderDetailView.as_view(), name="order_detail"),
	path("order/setStatus/", order.orderSetStatus, name="order_set_status"),

	path("room/", room.RoomList.as_view(), name="room_list"),
	path("room/add/", room.RoomAdd.as_view(), name="room_add"),
	path("room/<int:pk>/edit/", room.RoomEdit.as_view(), name="room_edit"),
	path("room/del/", room.RoomDel.as_view(), name="room_del"),

	path("roomtype/add/", room.RoomTypeAdd.as_view(), name="room_type_add"),
	path("roomtype/<int:pk>/edit/", room.RoomTypeEdit.as_view(), name="room_type_edit"),
	path("roomtype/del/", room.RoomTypeDel.as_view(), name="room_type_del"),

	path("notice/", notice.notice_list, name="notice_list"),
	path("notice/<int:pk>/", notice.notice_detail, name="notice_detail"),

	path("notice/manage/", notice.notice_manage, name="notice_manage"),
	path("notice/manage/add/", notice.NoticeAdd.as_view(), name="notice_add"),
	path("notice/manage/<int:pk>/edit/", notice.notice_edit, name="notice_edit"),
	path("notice/manage/<int:pk>/del/", notice.notice_del, name="notice_del"),

	path("login/", auth.Login.as_view(), name="login"),
	path("register/", auth.register, name="register"),
	path("logout/", auth.logout, name="logout"),
	path("alert/", auth.alert, name="alert"),

	path("account/", account.account_list, name="account_list"),
	path("account/add/", account.account_add, name="account_add"),
	path("account/<int:pk>/edit/", account.account_edit, name="account_edit"),
	path("account/<int:pk>/pwdedit/", account.account_pwd_edit, name="account_pwd_edit"),
	path("account/del/", account.account_del, name="account_del"),

	path("customer/", customer.customer_list, name="customer_list"),
	path("customer/add/", customer.customer_add, name="customer_add"),
	path("customer/<int:pk>/edit/", customer.customer_edit, name="customer_edit"),
	path("customer/<int:pk>/del/", customer.customer_del, name="customer_del"),

	path("db/", sql.recover_db, name="recover_db"),
	path("db/backup/", sql.backup_db, name="backup_db"),

]

mySite/urls.py
from django.conf import settings
# from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

urlpatterns = [
	re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}, name="media"),
	path('captcha/', include('captcha.urls')),
	path("", include("hotel.urls")),
]

hotel/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


# Create your models here.


class Room(models.Model):
	room_number = models.CharField(verbose_name="客房号", max_length=10, unique=True)
	room_type = models.ForeignKey(verbose_name="客房类型", to="RoomType", on_delete=models.SET_NULL, null=True,
	                              blank=True)
	room_status = models.SmallIntegerField(verbose_name="客房状态", choices=((0, "空闲"), (1, "已入住")),
	                                       default=0)

	def __str__(self):
		return self.room_number


class Customer(models.Model):
	customer_idNumber = models.CharField(verbose_name="身份证号", max_length=18)
	customer_creator = models.ForeignKey(verbose_name="住客创建人", to="Account", on_delete=models.CASCADE)
	customer_name = models.CharField(verbose_name="姓名", max_length=10)
	customer_phone = models.CharField(verbose_name="电话号码", max_length=11)
	customer_email = models.EmailField(verbose_name="邮箱")
	# customer_status = models.SmallIntegerField(verbose_name="状态", choices=((0, "正常"), (1, "已封禁")), default=0)


class Order(models.Model):
	order_idNumber = models.CharField(verbose_name="订单号", max_length=24)
	order_creator = models.ForeignKey(verbose_name="订单创建人", to="Account", on_delete=models.CASCADE)
	order_time = models.DateTimeField(verbose_name="下单时间", auto_now_add=True)
	order_check_in = models.DateField(verbose_name="住房起始日期")
	order_check_out = models.DateField(verbose_name="住房结束日期")
	order_status = models.SmallIntegerField(verbose_name="订单状态", default=0,
	                                        choices=((0, "已预订"), (1, "已入住"), (2, "已完成"), (3, "已取消")))
	order_price = models.DecimalField(verbose_name="订单价格", max_digits=8, decimal_places=2)
	order_rooms = models.ManyToManyField(verbose_name="订单房间", to="Room", through="OrderDetail")


class Account(models.Model):
	account_user = models.CharField(verbose_name="账户名", max_length=32, unique=True)
	account_name = models.CharField(verbose_name="昵称", max_length=32)
	account_phone = models.CharField(verbose_name="电话号码", max_length=11, unique=True)
	account_email = models.EmailField(verbose_name="邮箱", unique=True)
	account_password = models.CharField(verbose_name="密码", max_length=255)
	account_type = models.SmallIntegerField(verbose_name="账户类型", choices=((0, "顾客"), (1, "管理员")), default=0)
	# account_status = models.SmallIntegerField(verbose_name="账户状态", choices=((0, "正常"), (1, "已封禁")), default=0)

	def __str__(self):
		return self.account_user


class Notice(models.Model):
	notice_title = models.CharField(verbose_name="通知标题", max_length=40)
	notice_content = models.TextField(verbose_name="通知内容", max_length=300)
	notice_time = models.DateTimeField(verbose_name="发布时间", default=timezone.now)
	notice_expiration = models.DateTimeField(verbose_name="失效时间")
	notice_publisher = models.ForeignKey(verbose_name="发布人", to="Account", on_delete=models.CASCADE,
	                                     limit_choices_to={"account_type": 1})


class OrderDetail(models.Model):
	order = models.ForeignKey(verbose_name="订单", to="Order", on_delete=models.CASCADE)
	customer = models.ForeignKey(verbose_name="顾客", to="Customer", on_delete=models.CASCADE)
	room = models.ForeignKey(verbose_name="房间", to="Room", on_delete=models.CASCADE)


class RoomType(models.Model):
	roomType_name = models.CharField(verbose_name="房型名称", max_length=10)
	roomType_max = models.SmallIntegerField(verbose_name="最大入住人数", default=2)
	roomType_price = models.DecimalField(verbose_name="客房价格", max_digits=8, decimal_places=2)
	roomType_description = models.TextField(verbose_name="客房描述")
	roomType_img = models.ImageField(verbose_name="客房图片", upload_to="rooms_img/")

	def __str__(self):
		return self.roomType_name

	def get_absolute_url(self):
		return reverse("hotel:room_detail", kwargs={"pk": self.pk})

hotel/views/account.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from hotel.forms.forms import AccountModelForm, AccountAddModelForm
from hotel.models import Account
from hotel.utils.pagination import Pagination


def account_list(request):
	data_dict = {}
	search_data = request.GET.get("q", "")
	search_method = request.GET.get("m", "su")
	if search_data:
		method = {
			"su": "account_user__contains",
			"sp": "account_phone__contains",
			"se": "account_email__contains",
			"si": "id",
		}
		data_dict[method[search_method]] = search_data
	account_data = Account.objects.filter(**data_dict)
	page_object = Pagination(request, account_data, page_size=10)
	page_object.html()
	context = {
		"account_data": page_object.page_queryset,
		"page_string": page_object.page_string,
		"search_data": search_data,
		"search_method": search_method,
		"account_total": Account.objects.all().count(),
	}
	return render(request, "account_list.html", context)


def account_add(request):
	context = {
		"form": None,
		"title": "添加账户信息",
		"addMoreCtr": 1,
		"prv_info": "",
	}
	if request.method == "GET":
		context["form"] = AccountAddModelForm()
		return render(request, "info_edit.html", context)
	# print(request.POST)
	context["form"] = AccountAddModelForm(request.POST)
	if context["form"].is_valid():
		context["form"].save()

		if request.POST.get("addMore") == "1":
			context["form"] = AccountAddModelForm()
			context["prv_info"] = "用户 "+request.POST.get("account_user")+" 已添加"
			return render(request, "info_edit.html", context)
		return redirect("/account/")
	return render(request, "info_edit.html", context)


def account_edit(request, pk):
	context = {
		"form": None,
		"title": "修改账户信息",
		"addmoreCtr": 0,
	}
	if request.method == "GET":
		account_obj = Account.objects.filter(pk=pk).first()
		context["form"] = AccountModelForm(instance=account_obj)
		return render(request, "info_edit.html", context)
	account_obj = Account.objects.filter(pk=pk).first()
	form = AccountModelForm(request.POST, instance=account_obj)
	if form.is_valid():
		form.save()
		return redirect("/account/")
	return render(request, "info_edit.html", context)


def account_del(request):
	uid = request.GET.get("uid")
	if Account.objects.filter(id=uid).exists():
		Account.objects.filter(id=uid).delete()
		return JsonResponse({"status": True, "msg": "删除成功"})
	else:
		return JsonResponse({"status": False, "msg": "删除失败，数据不存在"})


def account_pwd_edit(request):
	return None

hotel/views/book.py
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from hotel.models import Room, RoomType, OrderDetail, Customer, Order


def get_available(start, end, room_type_id):
	all_room = Room.objects.filter(room_type_id=room_type_id)
	booked_room = OrderDetail.objects.filter(order__order_check_in__lt=end,
	                                         order__order_check_out__gt=start).values_list('room', flat=True)
	available_room = all_room.exclude(id__in=booked_room)
	# available_room_numbers = available_room.values_list('room_number', flat=True)
	return available_room


class BookList(View):

	def get(self, request):
		roomType_data = RoomType.objects.all()
		room_count = []
		today = timezone.now().strftime("%Y-%m-%d")
		tomorrow = (timezone.now() + timezone.timedelta(days=1)).strftime("%Y-%m-%d")
		error = request.GET.get("error", "")
		for room_type in roomType_data:
			room_count.append(get_available(today, tomorrow, room_type.id).count())
		context = {
			"roomType_data": zip(roomType_data, room_count),
			"today": today,
			"tomorrow": tomorrow,
			"error": error
		}
		return render(request, "book_list.html", context)

	def post(self, request):
		st = request.POST.get("st")
		ed = request.POST.get("ed")
		roomType_data = RoomType.objects.all()
		room_count = {}
		for room_type in roomType_data:
			room_count[room_type.id] = get_available(st, ed, room_type.id).count()
		# print(room_count)
		return JsonResponse({"room_availability": room_count})


class BookCheck(View):
	def get(self, request):
		book = request.session.get("book")
		room_type = RoomType.objects.filter(id=book["type_id"]).first()
		day = (timezone.datetime.strptime(book["ed"], "%Y-%m-%d") - timezone.datetime.strptime(book["st"],
		                                                                                       "%Y-%m-%d")).days
		context = {
			"room_type": room_type,
			"st": book["st"],
			"ed": book["ed"],
			"num": str(book["num"]),
			"price": int(book["num"]) * room_type.roomType_price * day,
			"customer_list": Customer.objects.filter(customer_creator_id=request.session.get("user")["id"]),
			"day": day
		}

		return render(request, "book_check.html", context)

	@transaction.atomic
	def post(self, request):
		# print(request.POST)
		book = request.session.get("book")
		st = book["st"]
		ed = book["ed"]
		num = int(book["num"])
		day = (timezone.datetime.strptime(ed, "%Y-%m-%d") - timezone.datetime.strptime(st, "%Y-%m-%d")).days
		room_type = RoomType.objects.filter(id=book["type_id"]).first()
		room = get_available(st, ed, room_type.id)
		if len(room) < num:
			return redirect("/book/?st=" + st + "&ed=" + ed + "&num=" + str(num) + "&error=3")
		now = timezone.datetime.now()
		order_id = now.strftime("%Y%m%d%H%M%S%f")
		price = int(book["num"]) * room_type.roomType_price * day
		order = Order.objects.create(order_idNumber=order_id, order_time=now, order_check_in=st,
		                             order_check_out=ed,
		                             order_status=0, order_price=price,
		                             order_creator_id=request.session.get("user")["id"])
		# print(order_id, now, st, ed, 0, price, request.session.get("user")["id"])
		for i in range(1, int(book["num"]) + 1):
			getStr = "room_" + str(i)
			customer_list = request.POST.getlist(getStr)
			for customer_id in customer_list:
				# print(customer_id, order_id, room[i - 1].id)
				OrderDetail.objects.create(customer_id=customer_id, order=order, room=room[i - 1])

		return redirect("/order/")


@csrf_exempt
def book_detail(request):
	# 获取post请求中的数据
	type_id = request.POST.get("type_id")
	st = request.POST.get("st")
	ed = request.POST.get("ed")
	num = int(request.POST.get("num"))
	if num > 5 or num < 1:
		return JsonResponse({"error": "1"})
	if st < timezone.now().strftime("%Y-%m-%d") or ed < st:
		return JsonResponse({"error": "2"})
	if num > get_available(st, ed, type_id).count():
		return JsonResponse({"error": "3"})

	request.session["book"] = {
		"type_id": type_id,
		"st": st,
		"ed": ed,
		"num": num
	}
	# 返回一个json响应，指向订单详细页的url
	return JsonResponse({"url": "/book/check/"})

hotel/views/customer.py
from django.shortcuts import render, redirect

from hotel.forms.forms import CustomerModelForm
from hotel.models import Customer
from hotel.utils.pagination import Pagination


def customer_list(request):
	data_dict = {}
	search_data = request.GET.get("q", "")
	search_method = request.GET.get("m", "sn")
	if search_data:
		method = {
			"sn": "customer_name__contains",
			"si": "customer_idNumber__contains",
			"sc": "customer_creator",
			"sp": "customer_phone__contains",
			"se": "customer_email__contains",
		}
		data_dict[method[search_method]] = search_data
	if request.session.get("user")["type"] == 1:
		total = Customer.objects.all().count()
	else:
		data_dict["customer_creator"] = request.session.get("user")["id"]
		total = Customer.objects.filter(**data_dict).count()
	customer_data = Customer.objects.filter(**data_dict)
	page_object = Pagination(request, customer_data, page_size=10)
	page_object.html()
	context = {
		"customer_data": page_object.page_queryset,
		"page_string": page_object.page_string,
		"search_data": search_data,
		"search_method": search_method,
		"customer_total": total,
	}
	return render(request, "customer_list.html", context)


def customer_add(request):
	context = {
		"form": None,
		"title": "添加住客信息",
		"addMoreCtr": 1,
		"prv_info": ""
	}
	if request.method == "GET":
		context["form"] = CustomerModelForm(initial={"customer_creator": request.session.get("user")["id"]})
		return render(request, "info_edit.html", context)
	context["form"] = CustomerModelForm(request.POST)
	if context["form"].is_valid():
		context["form"].save()
		if request.POST.get("addMore") == "1":
			context["form"] = CustomerModelForm()
			context["prv_info"] = "住客 " + request.POST.get("customer_name") + " 已添加"
			return render(request, "info_edit.html", context)
		return redirect("/customer/")
	return render(request, "info_edit.html", context)


def customer_edit(request, pk):
	if request.method == "GET":
		customer_obj = Customer.objects.filter(pk=pk).first()
		form = CustomerModelForm(instance=customer_obj)
		return render(request, "info_edit.html", {"form": form, "title": "修改住客信息"})
	customer_obj = Customer.objects.filter(pk=pk).first()
	form = CustomerModelForm(request.POST, instance=customer_obj)
	if form.is_valid():
		form.save()
		return redirect("/customer/")
	return render(request, "info_edit.html", {"form": form, "title": "修改住客信息"})


def customer_del(request, pk):
	Customer.objects.filter(id=pk).delete()
	return redirect("/customer/")

hotel/views/index.py
from django.shortcuts import render
from django.utils import timezone

from hotel.models import Notice


def index(request):
	last_notice = Notice.objects.filter(notice_expiration__gte=timezone.now()).order_by("-notice_time")
	user = request.session.get("info")
	# print(user)
	return render(request, "index.html", {"notice": last_notice, "user": user})

hotel/views/sql.py
import codecs
import subprocess

from django.http import HttpResponse
from django.shortcuts import render, redirect

from hotel.forms.forms import RecoverDBForm


def backup_db(request):
	output = subprocess.check_output(['python', 'manage.py', 'dumpdata'])
	with open('database_backup.json', 'wb') as file:
		file.write(output)

	response = HttpResponse(content_type='application/json')
	response['Content-Disposition'] = 'attachment; filename="database_backup.json"'
	response.write(output)
	return response


def recover_db(request):
	if request.method == "GET":
		form = RecoverDBForm()
		return render(request, 'recover_db.html', {'form': form})
	form = RecoverDBForm(request.POST, request.FILES)
	if form.is_valid():
		file = request.FILES.get('file')
		try:
			with open('database_backup.json', 'wb') as f:
				for chunk in file.chunks():
					chunk = chunk.decode('GBK').encode('utf-8')
					f.write(chunk)
			subprocess.check_output(['python', 'manage.py', 'loaddata', 'database_backup.json'])
		except Exception as e:
			print(e)
			return redirect('/alert/?code=405')
		return redirect('/alert/?code=201')
	return render(request, 'recover_db.html', {'form': form})

hotel/templates/alert.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="container">
{#        {% debug %}#}
        {% if code_type == 2 %}
            <div class="alert alert-success col-lg-6 mx-auto" role="alert">
                <h3 class="alert-success"><i class="bi bi-check-circle-fill me-3"></i>成功！</h3>
                <hr>
                <p class="mb-0">
                <p>{{ msg }}</p></p>
                <div class="modal-footer">即将在<span>10</span>秒后跳转至<a href="{{ link }}"
                                                                            class="alert-link">{{ link_text }}</a></div>
            </div>
        {% else %}
            <div class="alert alert-danger col-lg-6 mx-auto" role="alert">

                <h3 class="alert-danger"><i class="bi bi-exclamation-triangle-fill me-3"></i>错误！</h3>
                <hr>
                <p class="mb-0">
                <p>{{ msg }}</p></p>
                <div class="modal-footer">即将在<span>10</span>秒后跳转至<a href="{{ link }}"
                                                                            class="alert-link">{{ link_text }}</a></div>
            </div>
        {% endif %}
    </div>

{% endblock %}


{% block js %}

    <script>
        var time = 10;
        var timer = setInterval(function () {
            time--;
            if (time == 0) {
                clearInterval(timer);
                window.location.href = "{{ link }}";
            }
            document.querySelector('.modal-footer span').innerHTML = time;
        }, 1000);
    </script>

{% endblock %}
```

hotel/templates/book_detail.html
{% extends 'layout.html' %}
<div class="h1">订单详细</div>

hotel/templates/login.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}

{% block head %}
    <title>登录-Neko酒店</title>
{% endblock %}

{% block css %}
    <style>
        .card {
            margin: 10%;
        }

        .card .card-body .row {
            margin-top: 30px;
            padding-bottom: 10px;
        }


    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="card col-lg-4 col-auto">
                <h4 class="card-header">登录</h4>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <label>用户名</label>
                            {{ form.account_user }}
                            <span style="color: red;">{{ form.errors.account_user.0 }}</span>
                        </div>
                        <div class="mt-3">
                            <label>密码</label>
                            {{ form.account_password }}
                            <span style="color: red;">{{ form.errors.account_password.0 }}</span>
                        </div>
                        <div class="mt-3">
                            <label>验证码</label>
                            {{ form.captcha }}
                            <span style="color: red;">{{ form.errors.captcha.0 }}</span>
                            <div class="mt-4">
                                <button type="submit" class="btn btn-primary">登录</button>
                                <div class="d-inline-block float-end">
                                    <a href="{% url 'register' %}" class="btn btn-outline-success">注册</a>
                                    <a href="{% url 'register' %}" class="btn btn-outline-secondary">找回密码</a>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $('.captcha').click(function () {
            // console.log('click');
            $.getJSON("/captcha/refresh/", function (result) {
                $('.captcha').attr('src', result['image_url']);
                $('#id_captcha_0').val(result['key'])
            })
        });
    </script>
{% endblock %}

hotel/templates/notice_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    <title>{{ notice.notice_title }}</title>
{% endblock %}

{% block css %}
    <style>

    </style>
{% endblock %}

{% block content %}
    <div class="container">
    <div class="card">
        <div class="card-header">
            <span class="h3">{{ notice.notice_title }}</span>
            <a class="btn btn-outline-danger btn-sm float-end"
               href="javascript:window.opener=null;window.open('','_self');window.close();">关闭</a>
        </div>
        <div class="card-body">
            <div style="white-space: pre-line">{{ notice.notice_content }}</div>
        </div>
        <div class="card-footer">
            <span style="margin-right: 5rem">发布时间：{{ notice.notice_time }}</span>
            <span>发布人：{{ notice.notice_publisher }}</span>
        </div>

    </div>
{% endblock %}

{% block js %}
{% endblock %}

hotel/templates/order_detail.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        @media print {
            .no-print, .no-print * { /* 选择按钮和它的所有子元素 */
                display: none !important; /* 设置为不显示 */
            }

            .navbar-brand.d-print-block { /* 使用标签名和类名来选择brand元素 */
                display: block !important;
            }
        }

        }

    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card col-lg-7 col-md-10 ">
            <div class="card-header">
                <span class="h4">订单详情</span>
                <span class="float-end">
                    <button class="btn btn-outline-success no-print" onclick="window.print()">打印</button>
                    <button class="btn btn-outline-danger no-print" onclick="window.history.back()">返回</button>
                </span>

            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <p>订单号：{{ order.order_idNumber }}</p>
                        <p>订单创建人：{{ order.order_creator }}</p>
                        <p>下单时间：{{ order.order_time }}</p>
                        <p>住房起始日期：{{ order.order_check_in }}</p>
                        <p>住房结束日期：{{ order.order_check_out }}</p>
                        <p>订单状态：{{ order.get_order_status_display }}</p>
                        <p>订单价格：{{ order.order_price }}</p>
                    </div>
                    <div class="col">
                        <h5>订单房间</h5>
                        <ul>
                            {% regroup order_details by room as room_list %} <!-- 按照房间分组 -->
                            {% for room in room_list %} <!-- 遍历每个房间 -->
                                <li>
                                    <div>房间号：{{ room.grouper.room_number }}</div>
                                    <div>房间类型：{{ room.grouper.room_type }}</div>
                                    <div>顾客姓名：
                                        {% for order_detail in room.list %} <!-- 遍历每个房间下的订单详细对象 -->
                                            {{ order_detail.customer.customer_name }}{% if not forloop.last %},
                                            {% endif %}
                                            <!-- 显示住客姓名，并用逗号分隔 -->
                                        {% endfor %}
                                    </div>
                                </li>
                                <hr>
                            {% endfor %}
                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>

    </script>
{% endblock %}

hotel/templates/order_list.html
{% extends "layout.html" %}

{% block head %}
    <title>订单管理-Neko酒店</title>
{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">订单管理</h3>
            </div>
            <div class="card-body">
                <div>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped" style="margin-top: 20px;">
                            <thead>
                            <tr class="table-primary">
                                <th>id</th>
                                <th>订单号</th>
                                <th>创建人</th>
                                <th>创建时间</th>
                                <th>入住时间</th>
                                <th>退房时间</th>
                                <th>订单状态</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for obj in order_data %}
                                <tr>
                                    <td>{{ obj.id }}</td>
                                    <td>{{ obj.order_idNumber }}</td>
                                    <td>{{ obj.order_creator.account_user }}</td>
                                    <td>{{ obj.order_time }}</td>
                                    <td>{{ obj.order_check_in }}</td>
                                    <td>{{ obj.order_check_out }}</td>
                                    <td>{{ obj.get_order_status_display }}</td>

                                    <td>
                                        <a class="btn btn-primary btn-sm"
                                           href="{% url 'order_detail' obj.id %}">查看</a>
                                        {% if request.session.user.type == 1 %}

                                            <button type="button" class="btn btn-danger btn-sm btn-delete"
                                                    uid="{{ obj.id }}"
                                                    {% if obj.order_status >= 2 %}disabled{% endif %}>取消
                                            </button>
                                            {% if not obj.order_status == 0 %}
                                                <a class="btn btn-success btn-sm disabled">入住</a>
                                            {% else %}
                                                <a class="btn btn-success btn-sm"
                                                   href="{% url 'order_set_status' %}?id={{ obj.id }}&status=1">入住</a>
                                            {% endif %}
                                            {% if not obj.order_status == 1 %}
                                                <a class="btn btn-warning btn-sm disabled">退房</a>
                                            {% else %}
                                                <a class="btn btn-warning btn-sm"
                                                   href="{% url 'order_set_status' %}?id={{ obj.id }}&status=2">退房</a>
                                            {% endif %}
                                        {% endif %}

                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% if order_data %}
                            <ul class="pagination">
                                {{ page_string }}
                            </ul>
                        {% endif %}
                        <hr>
                        <div class="text-center">
                            {% if search_data %}
                                <span>搜索到{{ order_data|length }}条数据，</span>
                            {% endif %}
                            <span>共{{ order_total }}条数据</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="confrimDelModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">取消订单？</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    确认取消订单嘛？
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消操作</button>
                    <button type="button" id="btnConfirmDelete" class="btn btn-danger">确认取消订单</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID;

        $(function () {
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
        })


        function bindBtnDeleteEvent() {

            $(".btn-delete").click(function () {
                $("#confrimDelModal").modal('show');
                //获取当前行的ID
                CANCEL_ID = $(this).attr("uid");
            });
        }

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                // 点击确认删除按钮,将全局变量中设置的那个要删除的ID发送到后台
                $.ajax({
                    url: "{% url 'order_set_status' %}",      // => /order/delete/?uid=123
                    type: "GET",
                    dataType: "JSON",
                    data: {
                        id: CANCEL_ID,
                        status: 3
                    },
                    success: function (res) {
                        if (res.status) {
                            location.reload();
                        } else {
                            alert(res.error);
                        }
                    }
                })
            });
        }
    </script>
{% endblock %}